name: CICD UAT

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: [self-hosted, uat]
    
    env:
      IMAGE_NAME: yahsaka-punchin-web
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Set Commit Hash as Environment Variable
        id: set_commit_hash
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
      
      - name: Build docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.COMMIT_HASH }} .
      
      - name: Stop existing container
        run: |
          docker stop ${{ env.IMAGE_NAME }} || true
          docker rm ${{ env.IMAGE_NAME }} || true
      
      - name: Run new container
        run: |
          docker run -d --name ${{ env.IMAGE_NAME }} \
          -p 8000:8000 \
          --env-file=${{ secrets.PATH_ENV }} \
          ${{ env.IMAGE_NAME }}:${{ env.COMMIT_HASH }}
      
      - name: Cleanup unused Docker images
        run: docker image prune -a --force